### ISSUE TITLE
Installation fails with error AttributeError: module 'enum' has no attribute 'IntFlag'

### ISSUE THREAD

**Issue by awhan** [dirkmoors/pyejabberd#27]
Steps to reproduce
`python -m pip --log log.log install pyejabberd`

Traceback is as follows
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/m/pyejabberd_installation_bug/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 5, in <module>
        import distutils.core
      File "/usr/lib/python3.6/distutils/core.py", line 16, in <module>
        from distutils.dist import Distribution
      File "/usr/lib/python3.6/distutils/dist.py", line 9, in <module>
        import re
      File "/usr/lib/python3.6/re.py", line 142, in <module>
        class RegexFlag(enum.IntFlag):
    AttributeError: module 'enum' has no attribute 'IntFlag'
```

python version Python 3.6.4

OS and machine:
```
$ uname -a
Linux zero 4.15.3-2-ARCH #1 SMP PREEMPT Thu Feb 15 00:13:49 UTC 2018 x86_64 GNU/Linux
```
the distribution version on pypi is
```
$ python -m pip search pyejabberd
pyejabberd (0.2.11)  - A Python client for the Ejabberd XMLRPC API
```

**Comment by MuslimBeibytuly** [comment]
Any updates on this issue? Can't use with python3.8.2-alpine3.11 too

**Comment by wurstdog** [comment]
the same problem

enum34-1.1.2.tar.gz#sha256=2475d7fcddf5951e92ff546972758802de5260bf409319a9f1934e6bbc8b1dc7 (from pyejabberd) to build tracker '/private/var/folders/r9/2d2czxx10zl8jyzgrrxm0p1r0000gn/T/pip-req-tracker-_7pu2mix'
2020-10-22T16:27:54,202     Running setup.py (path:/private/var/folders/r9/2d2czxx10zl8jyzgrrxm0p1r0000gn/T/pip-install-ywvqdmot/enum34/setup.py) egg_info for package enum34
2020-10-22T16:27:54,202     Created temporary directory: /private/var/folders/r9/2d2czxx10zl8jyzgrrxm0p1r0000gn/T/pip-pip-egg-info-0qtc4g7u
2020-10-22T16:27:54,202     Running command python setup.py egg_info
2020-10-22T16:27:54,241     Traceback (most recent call last):
2020-10-22T16:27:54,241       File "<string>", line 1, in <module>
2020-10-22T16:27:54,241       File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 6, in <module>
2020-10-22T16:27:54,241         import distutils.core
2020-10-22T16:27:54,241       File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 16, in <module>
2020-10-22T16:27:54,241         from distutils.dist import Distribution
2020-10-22T16:27:54,241       File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 9, in <module>
2020-10-22T16:27:54,242         import re
2020-10-22T16:27:54,242       File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/re.py", line 143, in <module>
2020-10-22T16:27:54,242         class RegexFlag(enum.IntFlag):
2020-10-22T16:27:54,242     AttributeError: module 'enum' has no attribute 'IntFlag'
2020-10-22T16:27:54,244 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

pip search pyejabberd
pyejabberd (0.2.11)  - A Python client for the Ejabberd XMLRPC API

uname -ra
19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020
